import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MY BLOG',
  description: 'Generated by create next app',
}

const links = [
  { label: 'Home', href: '/' },
  { label: 'Blog', href: './blog' },
  { label: 'About', href: './about' },
  { label: 'Contact', href: './contact' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <Navbar links={links} />

          <div className="absolute top-[5rem] left-10 w-full">{children}</div>
        </div>
      </body>
    </html>
  )
}
